### ISSUE TITLE
GitHub Pages 를 이용한 미리보기?

### ISSUE THREAD

**Issue by copyrat90** [jbnu-vclab/jbnu-webgl-computer-graphics-lecture#16]
WebGL은 웹페이지에서 렌더링 할 수 있고,
GitHub 에서 GitHub Pages 라는 간단한 정적 웹페이지 호스팅 서비스를 제공하니,
GitHub Pages 에서 간단하게 미리보기 할 수 있도록 세팅하는 건 어떨까요?

테스트로 제가 포크한 저장소에서 GitHub Pages 를 활성화 시켜봤습니다. (원본 레포 링크로 수정됨)
<https://jbnu-vclab.github.io/jbnu-webgl-computer-graphics-lecture/lessons/18_light_abstraction/contents.html>

언더스코어`_` 가 들어간 폴더 내 파일을 포함하기 위해, 프로젝트 상단에 `.nojekyll` 파일을 추가하고
GitHub 레포지토리의 Settings > Pages 에서 활성화만 하면 됩니다.

만일 이렇게 한다면 `README.md` 에 `contents.html` 로 향하는 링크도 추가하면 좋을 것 같네요

**Comment by diskhkme** [comment]
감사합니다. 세팅을 해 두었고 각 레슨 페이지의 예제는 잘 들어가지는 것을 확인 하였습니다.
각 Lesson의 List를 정리해서 바로 볼 수 있도록 html 페이지를 하나 만들어 두는 것도 좋을 것 같네요 ㅎㅎ
