### ISSUE TITLE
[질문] `gl` 컨텍스트를 멤버로 저장하면 안되는 이유?

### ISSUE THREAD

**Issue by copyrat90** [jbnu-vclab/jbnu-webgl-computer-graphics-lecture#9]
# 질문

**7. Buffer Abstraction** 챕터의 아래 설명에 대해 의문이 생겼습니다.

> ## Advanced
> 1. 클래스 메소드에 첫 번째 인자로 `gl` 컨텍스트를 계속 참조하도록 하고 있습니다. 꼭 이렇게 귀찮게 해야하나, 그냥 전역변수로 두거나 멤버로 저장해 두면 안되나 하는 의문이 떠오르셨을 겁니다. (떠오르셨길 바랍니다.) 지금은 컨텍스트(캔버스)가 하나지만 이것이 꼭 하나라는 법은 없습니다. 동일한 데이터를 여러 캔버스에 그릴 수도 있겠죠. 그러한 경우를 생각하면 전역변수로 두는것, 멤버로 저장해 두는 것 모두 설계 관점에서 좋은 선택이 아닙니다.

현재 `VertexBuffer`, `IndexBuffer`와 `VertexArray` 클래스의 구현을 보면,
생성자에서 특정한 `gl` 컨텍스트에 버퍼를 만들고, 그 버퍼의 `id`를 저장하고 있습니다.

그런데 이 `id`는 생성자에 들어왔던 `gl` 컨텍스트에 대해서만 의미가 있지, 또 다른 `gl` 컨텍스트에 대해서는 의미가 없습니다.
**(생성자에 들어왔던 `gl` 컨텍스트에서만 버퍼가 생성된 것이지, 다른 `gl` 컨텍스트에서는 버퍼가 생성된 적이 없습니다.)**

현재 구현대로라면 **특정 `gl` 컨텍스트에서만 의미 있는 `VertexArray` 객체가 생성되므로,
오히려 `gl` 컨텍스트를 멤버로 저장하여, 실수로 다른 `gl` 컨텍스트에서 사용하는 것을 막는 게 합당해 보입니다.**

# 테스트 코드

## 코드

2개의 `glContext*` 에 대해 `VertexArray` 객체를 재사용 할 수 없음을 보이는 예제 코드입니다.

**test.html**
```html
<html>
<head>
  <link type="text/css" href="../../resources/webgl-tutorials.css" rel="stylesheet" />
</head>
<body>
  <!-- 캔버스를 2개 생성 -->
  <div>Canvas #1</div>
  <canvas id="c1"></canvas>
  <div>Canvas #2</div>
  <canvas id="c2"></canvas>
</body>
</html>

<script src="../../resources/webgl-utils.js"></script>
<script src="../../resources/webgl-lessons-ui.js"></script>
<script type="module" src="test.js"></script>
```

**test.js**
```js
"use strict";

import VertexBuffer from '../_classes/VertexBuffer.js';
import IndexBuffer from '../_classes/IndexBuffer.js';
import VertexArray  from '../_classes/VertexArray.js';

const vertexShaderSource = `#version 300 es
in vec4 a_position;

void main() {
  gl_Position = a_position;
}
`;

const fragmentShaderSource = `#version 300 es
precision highp float;
out vec4 outColor;

void main() {
  outColor = vec4(0.0,0.0,1.0,1.0);
}  
`;

function main() {
  // 1번 캔버스에 대한 `glContext1`
  const canvas1 = document.querySelector("#c1");
  const glContext1 = canvas1.getContext("webgl2");
  if (!glContext1) {
    return;
  }
  // 2번 캔버스에 대한 `glContext2`
  const canvas2 = document.querySelector("#c2");
  const glContext2 = canvas2.getContext("webgl2");
  if (!glContext2) {
    return;
  }

  const positions = [
      -1.0, 1.0,   // 0 vert
      -1.0, 0.75,  // 1
      -0.75, 1.0   // 2
  ];

  // `glContext1`에 대한 `triVA` 생성
  const triVA = new VertexArray(glContext1);
  const triVB = new VertexBuffer(glContext1, positions);
  triVA.AddBuffer(glContext1, triVB, [2], [false])

  const program = webglUtils.createProgramFromSources(glContext1, [vertexShaderSource, fragmentShaderSource]);
  glContext1.useProgram(program);

  // [OK] `glContext1`에 대해 정상 작동
  glContext1.drawArrays(glContext1.TRIANGLES, 0, 3);

  // [ERROR] `glContext2`는 buffer 생성된 적이 없으므로, 오류 발생.
  triVA.Bind(glContext2);
  triVB.Bind(glContext2);
  glContext2.useProgram(program);
  glContext2.drawArrays(glContext2.TRIANGLES, 0, 3);
}

main();
```

## 실행 결과

`Canvas #1`에는 삼각형이 정상적으로 그려지나,
`Canvas #2`에는 `object does not belong to this context` 라는 오류가 나면서 삼각형이 그려지지 않습니다.

![image](https://user-images.githubusercontent.com/34793045/193378053-9e5782e2-6388-4a38-ada7-bcb533a17aac.png)

**Comment by diskhkme** [comment]
넵 맞습니다. 아래 두 개의 링크에서 보실 수 있는 것처럼, 서로 다른 컨텍스트에서 생성한 객체들은 서로 공유할 수 없습니다.

- https://stackoverflow.com/questions/9122361/is-it-possible-to-have-two-webgl-contexts-on-the-same-page
- https://webglfundamentals.org/webgl/lessons/ko/webgl-multiple-views.html

제가 설계한 구조가 의미가 있으려면 최종적으로 각 컨텍스트를 위한 Renderer 추상화 계층을 새로 설계해서 집어넣어야 의미가 있을 것 같습니다. 현재 상태에서는 그렇지 않기 때문에 질문하신 분이 지적한 것이 맞는 이야기입니다.

한 가지 생각해 볼 만한 점은 Renderer 계층을 추가하지 않고 언급하신대로 gl을 멤버로 추가하게 된다면 어떤 버퍼가 어느 캔버스에 그려질 데이터인지를 관리하기 어렵다는 점입니다. 이러한 관리를 위해서 Renderer 계층을 만드는 것이기도 하고요.

어찌되었건 강의 자료에서는 다중 컨텍스트를 사용하지 않으니 현재 코드가 비효율적인 것은 사실입니다.

**Comment by copyrat90** [comment]
답변 감사드립니다. 추가로 질문이 있습니다.

실제로 반드시 다중 컨텍스트를 사용해야 하는 경우가 있는지 궁금합니다.
동일 데이터를 여러 컨텍스트에 그리기 위해 따로 버퍼를 마련하는 것은 VRAM 낭비가 되지 않을까 싶습니다.

2번째 링크해주신 글을 보니, WebGL의 경우 거대한 `canvas`를 1개 두고 내부에 `div` 를 나눠 그리는 방식으로 컨텍스트를 1개만 사용할 수 있는 것 같은데,
다른 환경(다른 OS / 그래픽스 라이브러리 등...)에서는 실제로 다중 컨텍스트를 활용하는 경우가 있을까요?

**Comment by diskhkme** [comment]
다중 컨텍스트를 사용할지 말지 여부는 환경에 따른 것은 아닐 것 같고, 만들고자 하는 것이 무엇인지에 따라 결정이 되는 문제일 것 같습니다.

흔하지 않은 경우이긴 하겠지만(저도 구체적인 사례를 좀 찾아보려 했는데 쉽지 않네요) 절대 사용할 일은 없다고 단정지을 수는 없겠죠.

**Comment by copyrat90** [comment]
그렇군요. 라이브러리는 다양한 용례에 대응해야하니, 다중 컨텍스트도 가능하다면 막을 이유는 없겠네요.
답변 감사드립니다.
